baseurl = "miesl채nnest채.fi"
languageCode = "fi"
defaultContentLanguage = "fi"
title = "Mies l채nnest채"
summaryLength = 30
timeout = 100000

[markup.goldmark.renderer]
unsafe= true


# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]
